apiVersion: apps/v1
kind: Deployment
metadata:
   name: accuknox-kub
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: accuknoxkub
              image: accuknox
              imagePullPolicy: Never
              ports:
                - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  name: accuknox-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499