apiVersion: apps/v1
kind: Deployment
metadata:
   name: accuknox-kub
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: accuknoxpra
   template:
      metadata:
         labels:
            app: accuknoxpra

      spec:
         containers:
            - name: accuknox-cont
              image: accuknox:latest
              imagePullPolicy: Never
              ports:
                - containerPort: 4499
